#compiles thr typescript code
FROM node:14.16.0 AS builder
WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig*.json ./
COPY  ./src ./src
RUN npm i --quiet && npm run build


FROM node:14.16.0-alpine3.13
RUN addgroup app && adduser -S -G app app
USER app
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV API_URL = https://api.myapp.com/ 
EXPOSE 4000
COPY --from=builder /usr/src/app/dist ./dist
CMD npm start
